Standard doubly linked list implementation PR
NickGeorgiev/sdp-kn-20-21-playground pull request #1
Opened 2020-10-13 17:37 UTC by 0tpg

2020-10-13 21:13 UTC, NickGeorgiev requested changes
Като цяло е добре. Има някои неща, които си изпуснал и е добре да ги оправиш. Също така гледам, че си започнал Move семантиката, така че напиши си и move assignment оператора, а не би било зле и да понапишеш малко тестове - с doctest би било най-добре, но поне един main в който да извикваш различни сценарии, за да си сигурен и за себе си, че работят, не само за нас.

2020-10-13 21:13 UTC, NickGeorgiev commented on group4/81966_Georgi_Gerginov/DLList/dllist.cpp
> +    : value{_value} {}
Качи го, моля те, на горния ред и си дооправи идентацията. Също така какви стойности задаваш на next и prev?

2020-10-13 21:13 UTC, NickGeorgiev commented on group4/81966_Georgi_Gerginov/DLList/dllist.cpp
> +    }
Аз бих го направил по класическия начин с помощен указател. Така, когато стигнеш последния елемент на списъка, последния Node ще успееш ли да го изтриеш?

2020-10-13 21:13 UTC, NickGeorgiev commented on group4/81966_Georgi_Gerginov/DLList/dllist.cpp
> +    : DLList{0, nullptr, nullptr} {}
Първия ми коментар важи за всички инициализиращи списъци

2020-10-13 21:13 UTC, NickGeorgiev commented on group4/81966_Georgi_Gerginov/DLList/dllist.cpp
> +    : m_length{length}, m_start{start}, m_end{end} {}
Няма нужда от такъв конструктор

2020-10-13 21:13 UTC, NickGeorgiev commented on group4/81966_Georgi_Gerginov/DLList/dllist.cpp
> +    if(!m_start -> next) {
А ако списъкът е изцяло празен?

2020-10-13 21:13 UTC, NickGeorgiev commented on group4/81966_Georgi_Gerginov/DLList/dllist.cpp
> +    if(!m_end -> prev) {
И тук каво ще стане, ако списъкът е празен?

2020-10-13 21:13 UTC, NickGeorgiev commented on group4/81966_Georgi_Gerginov/DLList/dllist.cpp
> +}
Добавяй по един празен ред накрая във файловете, за да се знае къде е края на файла.

2020-10-14 09:32 UTC, 0tpg commented on group4/81966_Georgi_Gerginov/DLList/dllist.cpp
> +}
Тоест да сложа още едно \n?

2020-10-14 09:34 UTC, 0tpg commented on group4/81966_Georgi_Gerginov/DLList/dllist.cpp
> +    }
Няма, но така последния Node остава единствен в списъка и затова го трия след блока, опитвах се да го направя без помощен указател.

2020-10-14 10:18 UTC, 0tpg commented on group4/81966_Georgi_Gerginov/DLList/dllist.cpp
> +    if(!m_start -> next) {
Нещо ще се счупи още на ред 71, защото length  е size_t. Най-лесното решение ми се струва да сложим всичко от 71 ред надолу в if(m_start)?

2020-10-14 19:36 UTC, NickGeorgiev commented on group4/81966_Georgi_Gerginov/DLList/dllist.cpp
> +    if(!m_start -> next) {
Да, това е добра идея. Като цяло добре е да намаляш размера само когато си сигурен, че ще махнеш нещо. В противен случай и да не прескочиш size_t пак ще е грешно

2020-10-14 19:36 UTC, NickGeorgiev commented on group4/81966_Georgi_Gerginov/DLList/dllist.cpp
> +    }
Ок, остави го така, само че ако ще ползваш този метод на друго място, освен в деструктора, то не забравяй да оправиш m_start и m_end, а заедно с тях и дължината.

2020-10-15 08:41 UTC, NickGeorgiev approved these changes

2020-10-15 18:19 UTC, merged