Skip List PR
NickGeorgiev/sdp-kn-20-21-playground pull request #11
Opened 2020-10-18 14:28 UTC by RadostinaYosheva

# Description
Implementation of basic skip list with one level.

# Changes
[State the code changes if there are any]

# Checklist
- [x] Code is in the proper folder
- [x] Proper label is added
- [x] At least one approving review is present

2020-10-22 07:53 UTC, NickGeorgiev requested changes
1. Изглежда добре
2. Иска ми се да се пробваш да му напишеш и unit тестове

2020-10-22 07:53 UTC, NickGeorgiev commented on group4/81987_Radostina_Yosheva/skipList.cpp
> +    if (prev == nullptr)
Сравнението е излишно

2020-10-22 07:53 UTC, NickGeorgiev commented on group4/81987_Radostina_Yosheva/skipList.cpp
> +        if (size == 0)
Скобите къде изчезнаха?

2020-10-22 07:53 UTC, NickGeorgiev commented on group4/81987_Radostina_Yosheva/skipList.cpp
> +    end = curr;
Това е защото?

2020-10-22 07:53 UTC, NickGeorgiev commented on group4/81987_Radostina_Yosheva/skipList.cpp
> +    }
Могат ли да се обединят?

2020-10-22 07:53 UTC, NickGeorgiev commented on group4/81987_Radostina_Yosheva/skipList.cpp
> +void SkipList::printSkips(){
Това защо ви е?

2020-10-22 07:53 UTC, NickGeorgiev commented on group4/81987_Radostina_Yosheva/skipList.cpp
> +    clearSkips();
Имай предвид, че това не е най-удачния начин, понеже така обхождаш списъка два пъти, макар и през skip указателите обхождането да е по-кратко

2020-10-22 07:53 UTC, NickGeorgiev commented on group4/81987_Radostina_Yosheva/skipList.cpp
> +}
Това няма място при дефиницията на класа, обособи го в нов файл, даже направо с unit тестове

2020-10-22 07:53 UTC, NickGeorgiev commented on group4/81987_Radostina_Yosheva/skipList.h
> +#endif
Слагай по един нов ред накрая на файловете където няма

2020-10-24 19:06 UTC, RadostinaYosheva commented on group4/81987_Radostina_Yosheva/skipList.cpp
> +void SkipList::printSkips(){
За да видя дали съм насочила правилно skip указателите

2020-10-24 19:08 UTC, RadostinaYosheva commented on group4/81987_Radostina_Yosheva/skipList.cpp
> +    }
Могат, просто при писане на кода ги отделих на случаи и не съм ги рефакторирала

2020-10-24 19:27 UTC, RadostinaYosheva commented on group4/81987_Radostina_Yosheva/skipList.cpp
> +    end = curr;
Обновявам новия краен указател така, за да може последния скип да е към него

2020-10-24 19:28 UTC, RadostinaYosheva commented on group4/81987_Radostina_Yosheva/skipList.cpp
> +        if (size == 0)
По-прегледно е без скоби за толкова малко нещо

2020-10-24 19:28 UTC, RadostinaYosheva commented on group4/81987_Radostina_Yosheva/skipList.cpp
> +    if (prev == nullptr)
Излишно е, но е по-интуитивно, според мен

2020-10-27 17:50 UTC, NickGeorgiev commented on group4/81987_Radostina_Yosheva/skipList.cpp
> +        if (size == 0)
Всъщност е ужасно така. Така ако твоя ред изчезне поради някаква причина, компилатора ще счита първия срещнат ред, че е в блока на if-a. Още повече, че след известно време ще решиш да се върнеш към някой такъв блок и без да се усетиш ще добавиш още нещо и ще забравиш за скобите, което ще доведе до това новия ти ред да се изпълнява винаги.
Да не говорим, че ще свикнеш да ги пишеш по този начин и после ще ти е трудно отучването.

2020-10-27 17:51 UTC, NickGeorgiev commented on group4/81987_Radostina_Yosheva/skipList.cpp
> +    end = curr;
Въпросът ми е защо трябва всеки път да циклиш до края на списъка, за да преместиш края, когато може да се преместиш веднага. Също така, сигурна ли си, че ако start го няма, проверката в цикъла ще работи?

2020-10-27 17:53 UTC, NickGeorgiev commented on group4/81987_Radostina_Yosheva/skipList.cpp
> +    }
Ами рефакторирай го, моля те. По-прегледно е

2020-10-27 17:53 UTC, NickGeorgiev commented on group4/81987_Radostina_Yosheva/skipList.cpp
> +void SkipList::printSkips(){
Вече не ти е нужно, може да го махнеш

2020-10-27 17:57 UTC, NickGeorgiev commented on group4/81987_Radostina_Yosheva/skipList.cpp
> +    if (prev == nullptr)
Въпрос на гледна точка е. Бих казал, че е равносилно на това `bool a = true; return a == true;` Имай предвид обаче, че в други езици има методи като empty/present/blank и прочие, които са за предпочитане пред сравняването с nil_value-то в езика

2026-03-17 11:13 UTC, closed without merging