Implemented a skip linked list. Added tests.
NickGeorgiev/sdp-kn-20-21-playground pull request #16
Opened 2020-10-18 21:00 UTC by KaloyanKutiyski

# Description
Skip link list with a method for adding elements and resetting skips when the length of the list is changed

# Changes

# Checklist
Make sure all checks are passed

- [ ] Code is in the proper folder
- [ ] Proper label is added
- [ ] At least one approving review is present

2020-10-24 11:57 UTC, NickGeorgiev requested changes
1. Изключително много проверки
2. Присъствие на magic numbers, които не става ясно от къде идват
3. **continue/break не искам да присъстват на нито едно място в кода**
4. **Този return, който слагаш на почти всеки един метод искам да изчезне**
5. **Искам всеки един метод да бъде преправен да използва минимално количество if блокове и цикли**
6. **Не съм отбелязал всички места, които повтарят едни и същи грешки, така че веднъш посочени, искам да бъдат оправени навсякъде**

2020-10-24 11:57 UTC, NickGeorgiev commented on group4/81978_KaloyanKutiyski/SkipList_basedOnLinkList/LList/LList.hpp
> +class LList {
Не бих го кръстил LList, понеже е объркващо. SkipList е по-подходящо

2020-10-24 11:57 UTC, NickGeorgiev commented on group4/81978_KaloyanKutiyski/SkipList_basedOnLinkList/LList/LList.hpp
> +struct Box {
Вкарай я в класа

2020-10-24 11:57 UTC, NickGeorgiev commented on group4/81978_KaloyanKutiyski/SkipList_basedOnLinkList/LList/LList.cpp
> +    return;
WHY? А и какво става със скип указателите?

2020-10-24 11:57 UTC, NickGeorgiev commented on group4/81978_KaloyanKutiyski/SkipList_basedOnLinkList/LList/LList.cpp
> +bool LList<T>::empty() {
Константен може би?

2020-10-24 11:57 UTC, NickGeorgiev commented on group4/81978_KaloyanKutiyski/SkipList_basedOnLinkList/LList/LList.cpp
> +void LList<T>::pushBack(const T& value) {
Това не позволява ли да генерирам ненареден SkipList?

2020-10-24 11:57 UTC, NickGeorgiev commented on group4/81978_KaloyanKutiyski/SkipList_basedOnLinkList/LList/LList.cpp
> +void LList<T>::pop() {
Това защо ти е?

2020-10-24 11:57 UTC, NickGeorgiev commented on group4/81978_KaloyanKutiyski/SkipList_basedOnLinkList/LList/LList.cpp
> +    if (!index) {
Аз не бих използваш имплицитно конвертиране

2020-10-24 11:57 UTC, NickGeorgiev commented on group4/81978_KaloyanKutiyski/SkipList_basedOnLinkList/LList/LList.cpp
> +            break;
Това може ли да си го спестим?

2020-10-24 11:57 UTC, NickGeorgiev commented on group4/81978_KaloyanKutiyski/SkipList_basedOnLinkList/LList/LList.cpp
> +}
Аз бих се опитал да направя метода по-четим. Малко много ми идват всички проверки, струва ми се, че могат да се съкратят

2020-10-24 11:57 UTC, NickGeorgiev commented on group4/81978_KaloyanKutiyski/SkipList_basedOnLinkList/LList/LList.cpp
> +        }
Тия изобщо не искам да ги виждам

2020-10-24 11:57 UTC, NickGeorgiev commented on group4/81978_KaloyanKutiyski/SkipList_basedOnLinkList/LList/LList.cpp
> +    return;
Защо???

2020-10-24 11:57 UTC, NickGeorgiev commented on group4/81978_KaloyanKutiyski/SkipList_basedOnLinkList/LList/LList.cpp
> +    // return count;
Това го изтрий

2020-10-24 11:57 UTC, NickGeorgiev commented on group4/81978_KaloyanKutiyski/SkipList_basedOnLinkList/LList/LList.cpp
> +void LList<T>::pushFront(const T& val) {
Продължавам да не разберам защо са ти тези методи

2020-10-24 11:57 UTC, NickGeorgiev commented on group4/81978_KaloyanKutiyski/SkipList_basedOnLinkList/LList/LList.cpp
> +LList<T> LList<T>::concat(const LList<T>& other)const {
Каква е разликата с предишното?

2020-10-24 11:57 UTC, NickGeorgiev commented on group4/81978_KaloyanKutiyski/SkipList_basedOnLinkList/LList/LList.cpp
> +void LList<T>::reverse() {
Тук обаче ще трябва да адресираш и скиповете

2020-10-24 11:57 UTC, NickGeorgiev commented on group4/81978_KaloyanKutiyski/SkipList_basedOnLinkList/LList/LList.cpp
> +    while (curr) {
Това не е ли същото като горната функция?

2020-10-24 11:57 UTC, NickGeorgiev commented on group4/81978_KaloyanKutiyski/SkipList_basedOnLinkList/LList/LList.cpp
> +    if (size < 4) {
Тая 4ка от къде изниква?

2020-10-24 11:57 UTC, NickGeorgiev commented on group4/81978_KaloyanKutiyski/SkipList_basedOnLinkList/LList/LList.cpp
> +            curr = curr->skip;
Това как работи?

2020-10-24 11:57 UTC, NickGeorgiev commented on group4/81978_KaloyanKutiyski/SkipList_basedOnLinkList/LList/LList.cpp
> +    }
Като ще хвърляме exception, нека да е нещо смислено. Напиши си свои типове примерно или ползвай готовите

2020-10-24 11:57 UTC, NickGeorgiev commented on group4/81978_KaloyanKutiyski/SkipList_basedOnLinkList/LList/LList.cpp
> +        }
Искам да се минимизира количеството if-ове

2020-10-24 11:57 UTC, NickGeorgiev commented on group4/81978_KaloyanKutiyski/SkipList_basedOnLinkList/LList/LList.cpp
> +    return;
Караш ме да мисля, че този код не си го писал ти

2020-10-24 11:57 UTC, NickGeorgiev commented on group4/81978_KaloyanKutiyski/SkipList_basedOnLinkList/LList/LList.cpp
> +        return - 1;
Помисли си какъв може да бъде типа на метода, за да може да нямаш подобни върнати стойности. Какво пречи да сложа -1 като реален елемент от списъка?

2020-10-24 11:57 UTC, NickGeorgiev commented on group4/81978_KaloyanKutiyski/SkipList_basedOnLinkList/LList/LList.cpp
> +        curr = curr->skip;
Ако skip указателя го няма?

2020-10-24 11:57 UTC, NickGeorgiev commented on group4/81978_KaloyanKutiyski/SkipList_basedOnLinkList/LList/LList.cpp
> +        result += skipSize;
Мога ли да скоча на по-малка дължина?

2020-10-25 18:19 UTC, KaloyanKutiyski commented on group4/81978_KaloyanKutiyski/SkipList_basedOnLinkList/LList/LList.cpp
> +            curr = curr->skip;
Т.е. да напиша коментари?

2020-10-25 18:21 UTC, KaloyanKutiyski commented on group4/81978_KaloyanKutiyski/SkipList_basedOnLinkList/LList/LList.cpp
> +    if (size < 4) {
от x < 4 => sqrt(x) < 2 и скипове със стъпка sqrt(size) нямат смисъл. Предполагам трябваше да го запиша като коментар.

2020-10-28 23:24 UTC, NickGeorgiev commented on group4/81978_KaloyanKutiyski/SkipList_basedOnLinkList/LList/LList.cpp
> +    if (size < 4) {
Или ако беше качил смятането на дължината отгоре и да ползваш него

2020-10-28 23:25 UTC, NickGeorgiev commented on group4/81978_KaloyanKutiyski/SkipList_basedOnLinkList/LList/LList.cpp
> +            curr = curr->skip;
Не само. Не разбирам, защо тръгваш от последния елемент

2020-10-29 21:47 UTC, KaloyanKutiyski commented on group4/81978_KaloyanKutiyski/SkipList_basedOnLinkList/LList/LList.cpp
> +            curr = curr->skip;
Наистина странно. Реално значеше че скиповете не се ползват. Като го заместих с first работи коректно.

2020-10-29 22:10 UTC, closed without merging