Monika Lambeva 82017
NickGeorgiev/sdp-kn-20-21-playground pull request #20
Opened 2020-10-22 07:05 UTC by MLambeva

# Description
[Add brief description of the problem]

# Changes
[State the code changes if there are any]

# Checklist
Make sure all checks are passed

- [ ] Code is in the proper folder
- [ ] Proper label is added
- [ ] At least one approving review is present

2020-10-24 15:29 UTC, NickGeorgiev requested changes
1.**Идентацията да се оправи задължително. Кода е изключително труден за четене и проследяване, когато е неподреден**
2. Експлицитното извикване на this указателя е абсолютно излишно на доста места, обърнал съм ти внимание на първото
3. Иска ми се да напишеш няколко unit теста за двесвързания списък.
4. Обръщането на двусвързан списък стара тривиално, така че със сигурност го промени.
5. gitkeep и readme файловете за излишни от ПР-а, така че преманхни от клона си

2020-10-24 15:29 UTC, NickGeorgiev commented on group1/Monika_Lambeva_82017/DList/DList.cpp
> +if(other.first == nullptr)
if(!other.first)

2020-10-24 15:29 UTC, NickGeorgiev commented on group1/Monika_Lambeva_82017/DList/DList.cpp
> +    while(toCopy != nullptr)
По подобие на предишния коментар

2020-10-24 15:29 UTC, NickGeorgiev commented on group1/Monika_Lambeva_82017/DList/DList.cpp
> +        prevCopied = prevCopied->next;
Помисли как това може да стане по-кратко и да спестиш няколко reassignment-а на указателите

2020-10-24 15:29 UTC, NickGeorgiev commented on group1/Monika_Lambeva_82017/DList/DList.cpp
> +    this->first = nullptr;
Използвай инициализиращ списък

2020-10-24 15:29 UTC, NickGeorgiev commented on group1/Monika_Lambeva_82017/DList/DList.cpp
> +//box* getFirst()const
Това се надявам да не го видя откоментирано

2020-10-24 15:29 UTC, NickGeorgiev commented on group1/Monika_Lambeva_82017/DList/DList.cpp
> +void DList::pop()
Аз бих си преименувал метода, за да е ясно че махаме от началото

2020-10-24 15:29 UTC, NickGeorgiev commented on group1/Monika_Lambeva_82017/DList/DList.cpp
> +    this->first = saver;
Ако списъка е двусвързан, има ли смисъл от saver и какво се случва със свързаността на новото начало на списъка?

2020-10-24 15:29 UTC, NickGeorgiev commented on group1/Monika_Lambeva_82017/DList/DList.cpp
> +this->first = newElem;
Това искам да стане на най-много 6 реда вместо 8.

2020-10-24 15:29 UTC, NickGeorgiev commented on group1/Monika_Lambeva_82017/DList/DList.cpp
> +        (*this).push(other);
(*this) защо ти е?

2020-10-24 15:29 UTC, NickGeorgiev commented on group1/Monika_Lambeva_82017/DList/DList.cpp
> +newElem->prev = last;
Помисли каква промяна в архитектурата на списъка може да направш, за да бъде добавянето на елемент към списъка, дали отпред или отзад да бъде за константно време, а не линейно, както е в момента

2020-10-24 15:29 UTC, NickGeorgiev commented on group1/Monika_Lambeva_82017/DList/DList.cpp
> +int DList::count(box* l, int x)
Не съм сигурен, че разбирам какво точно прави този метод

2020-10-24 15:29 UTC, NickGeorgiev commented on group1/Monika_Lambeva_82017/DList/DList.cpp
> +int DList::countFromBegin(const int& x)
Гадая, но ако това има нещо общо с горния метод, защо не използваш него?

2020-10-24 15:29 UTC, NickGeorgiev commented on group1/Monika_Lambeva_82017/DList/DList.cpp
> +box* DList::range(int x, int y)
Защо трябва да си счупиш капсулацията като върнеш началото?

2020-10-24 15:29 UTC, NickGeorgiev commented on group1/Monika_Lambeva_82017/DList/DList.cpp
> +    }
Това за какво ти е, щом не го ползваш?

2020-10-24 15:29 UTC, NickGeorgiev commented on group1/Monika_Lambeva_82017/DList/DList.cpp
> +    return *this;
Мога ли да си спестя някой от append-ите?

2020-10-24 15:29 UTC, NickGeorgiev commented on group1/Monika_Lambeva_82017/DList/DList.cpp
> +}
Why????

2020-10-24 15:29 UTC, NickGeorgiev commented on group1/Monika_Lambeva_82017/DList/DList.cpp
> +box* prev = nullptr;
Ти не работеше ли с двусвързан списък, защо ти е нужен предходния елемент? Не можем ли да го разберем от текущия?

2020-10-24 15:29 UTC, NickGeorgiev commented on group1/Monika_Lambeva_82017/DList/DList.cpp
> +}
В метода до колкото разбирам трябва да ги премахнеш. Това, което правиш е да ги изкараш от списъка, но не и да ги изтриеш, което води до memory leak, а такъв не искаме да получаваме в нинакъв случай

2020-10-24 15:29 UTC, NickGeorgiev commented on group1/Monika_Lambeva_82017/DList/DList.cpp
> +        curr = next;
Така не правиш ли swap на двата указателя на възела? Ако да, мога ли да спестя повечето редове и да ги заместя само с един ред?

2020-10-24 15:29 UTC, NickGeorgiev commented on group1/Monika_Lambeva_82017/DList/DList.cpp
> +void DList::removeAllDuplicates()
Това не е ли същото като removeAll?

2020-10-24 15:29 UTC, NickGeorgiev commented on group1/Monika_Lambeva_82017/DList/DList.cpp
> +    curr->next->prev = prev;
Можем ли да обърнем логиката и да премахнем ранния return?

2020-10-24 15:29 UTC, NickGeorgiev commented on group1/Monika_Lambeva_82017/DList/DList.cpp
> +        else if(next == nullptr && otherCurr->data >= curr->data)
Ако next е nullptr още на предишната стъпка ще ти гръмне кода

2020-10-24 15:29 UTC, NickGeorgiev commented on group1/Monika_Lambeva_82017/DList/DList.cpp
> +            next = this->first;
Искам да помислиш как да съкратиш фрагмента

2020-10-24 15:29 UTC, NickGeorgiev commented on group1/Monika_Lambeva_82017/DList/DList.cpp
> +}
Слагай по един нов ред накрая на всеки файл

2020-10-24 15:29 UTC, NickGeorgiev commented on group1/Monika_Lambeva_82017/DList/Dlist.h
> +struct box
Класовете ги пишем с главна буква. Също така искам да го вкараш при класа

2020-10-24 15:29 UTC, NickGeorgiev commented on group1/Monika_Lambeva_82017/DList/Dlist.h
> +int count(box* l, int x);
Константен метод

2020-10-24 15:29 UTC, NickGeorgiev commented on group1/Monika_Lambeva_82017/DList/Dlist.h
> +int countFromBegin(const int& x);
Константен метод

2020-10-24 15:29 UTC, NickGeorgiev commented on group1/Monika_Lambeva_82017/DList/Dlist.h
> +
Нямам представа защо си ги сложила

2020-10-24 15:29 UTC, NickGeorgiev commented on group1/Monika_Lambeva_82017/list/list.cpp
> +   first = nullptr;
И тук да не забравим инициализиращия списък

2020-10-24 15:29 UTC, NickGeorgiev commented on group1/Monika_Lambeva_82017/list/list.cpp
> +   return *this;
При self-assignment какво правим?

2020-10-24 15:29 UTC, NickGeorgiev commented on group1/Monika_Lambeva_82017/list/list.cpp
> +    }
Ако стартираш с начални стойности на first - nullptr ще си спестиш тези проверки

2020-10-24 15:29 UTC, NickGeorgiev commented on group1/Monika_Lambeva_82017/list/list.cpp
> +    this->first = newBox;
Искам да стане на един ред

2020-10-24 15:29 UTC, NickGeorgiev commented on group1/Monika_Lambeva_82017/list/list.cpp
> +int List::count(int x)
Искам да разберем размера на списъка за константно, а не линейно време

2020-10-24 15:29 UTC, NickGeorgiev commented on group1/Monika_Lambeva_82017/list/list.cpp
> + box* last = this->first;
Отново ти задавам въпроса с архитектурните промени по списъка, които ще спестят повечето обхожданея

2020-10-24 15:29 UTC, NickGeorgiev commented on group1/Monika_Lambeva_82017/list/list.cpp
> +(*this).insertAt(other, counter);
Тук даже го обхождаш няколко пъти, когато това може да стане без нито едно обхождане

2020-10-24 15:29 UTC, NickGeorgiev commented on group1/Monika_Lambeva_82017/list/list.cpp
> +    }
Искам да обърнеш логиката, за да няма early return

2020-10-24 15:29 UTC, NickGeorgiev commented on group1/Monika_Lambeva_82017/list/list.cpp
> +    }
Искам да обърнеш логиката, за да няма early return

2020-10-24 15:29 UTC, NickGeorgiev commented on group1/Monika_Lambeva_82017/list/list.cpp
> +    return newList;
Искам да стане на 3 реда

2020-10-24 15:29 UTC, NickGeorgiev commented on group1/Monika_Lambeva_82017/list/list.h
> +struct box
Отново името на класа да не забравиш

2020-10-24 15:29 UTC, NickGeorgiev commented on group1/Monika_Lambeva_82017/list/list.h
> +int count(int x);
Константна може би?

2020-10-24 15:29 UTC, NickGeorgiev commented on group1/Monika_Lambeva_82017/list/list.h
> +int get_ith(int n);
Тази може би също

2020-10-24 16:38 UTC, MLambeva commented on group1/Monika_Lambeva_82017/list/list.cpp
> +(*this).insertAt(other, counter);
В класа си имам само указател към първи елемент и не се сещам как бих го направила без да знам кой е последният елемент.

2020-10-24 17:19 UTC, MLambeva commented on group1/Monika_Lambeva_82017/DList/DList.cpp
> +void DList::removeAllDuplicates()
"removeAll" изтрива всички срещания на елемента "х".
"removeAllDuplicates" изтрива всички дублиращи се елементи.

2020-10-24 17:21 UTC, MLambeva commented on group1/Monika_Lambeva_82017/DList/DList.cpp
> +        curr = next;
Класът ми е с един указател за начало. Това не променя ли нещата?

2020-10-29 17:58 UTC, NickGeorgiev requested changes
Оправи си дереференцията на this указателя, прескачането на елемента и копирането на списъка. За останалите неща си погледни коментарите, утре сутринта ако си ги променила, ще го слея

2020-10-29 17:58 UTC, NickGeorgiev commented on group1/Monika_Lambeva_82017/DList/DList.cpp
> +        this->first->next=this->first->next->next;
Защо прескачаш елемента?

2020-10-29 17:58 UTC, NickGeorgiev commented on group1/Monika_Lambeva_82017/DList/DList.cpp
> +        }
Идеята е обхождането при добавяне на елемент в края да изчезне. Аз все още не виждам промяна в архитектурата, за да стане константно.

2020-10-29 17:58 UTC, NickGeorgiev commented on group1/Monika_Lambeva_82017/DList/DList.cpp
> +    (*this).push(x);
Тук си го забравила

2020-10-29 17:58 UTC, NickGeorgiev commented on group1/Monika_Lambeva_82017/DList/DList.cpp
> +    return (*this).count(this->first, x);
И тук също

2020-10-29 17:58 UTC, NickGeorgiev commented on group1/Monika_Lambeva_82017/DList/DList.cpp
> +    (*this).push(y);
И тук

2020-10-29 17:58 UTC, NickGeorgiev commented on group1/Monika_Lambeva_82017/DList/DList.cpp
> +Box* DList::range(int x, int y)
Недей да му чупиш капсулацията

2020-10-29 17:58 UTC, NickGeorgiev commented on group1/Monika_Lambeva_82017/DList/DList.cpp
> +       (*this).push_back(helper->data);
И тук

2020-10-29 17:58 UTC, NickGeorgiev commented on group1/Monika_Lambeva_82017/DList/DList.cpp
> +                    (*this).pop();
И тук

2020-10-29 17:58 UTC, NickGeorgiev commented on group1/Monika_Lambeva_82017/DList/DList.cpp
> +        curr = next;
Не, аз говоря за указателите на всяка кутия, а не за указателя на самия списък

2020-10-29 17:58 UTC, NickGeorgiev commented on group1/Monika_Lambeva_82017/list/list.cpp
> +    if(other.first)
Бъди сигурна, че началото ти е nullptr. Така сега си си махнала проверката за началото и в крайна сметка началото ти остава неинициализирано. Или преди да извикаш метода го занули, или тук го занулявай.

2020-10-29 17:58 UTC, NickGeorgiev commented on group1/Monika_Lambeva_82017/list/list.cpp
> +      (*this).push(other);
И тук

2020-10-29 17:58 UTC, NickGeorgiev commented on group1/Monika_Lambeva_82017/list/list.cpp
> +(*this).insertAt(other, counter);
Ами можеш ли да направиш така, че да го знаеш без да трябва да броиш всеки път?

2020-10-29 17:58 UTC, NickGeorgiev commented on group1/Monika_Lambeva_82017/list/list.cpp
> +        (*this).push_back(helper->data);
И тук

2020-10-29 17:58 UTC, NickGeorgiev commented on group1/Monika_Lambeva_82017/list/list.cpp
> +    (*this).append(other);
И тук

2020-10-30 17:01 UTC, NickGeorgiev submitted a review, later dismissed

2020-10-30 17:14 UTC, NickGeorgiev submitted a review, later dismissed

2020-10-30 17:19 UTC, NickGeorgiev approved these changes

2020-10-30 17:19 UTC, merged