Added Skip list
NickGeorgiev/sdp-kn-20-21-playground pull request #9
Opened 2020-10-18 11:15 UTC by mollova

# Description
Skip list

# Changes
first commit

# Checklist
Make sure all checks are passed

- [ ] Code is in the proper folder
- [ ] Proper label is added
- [ ] At least one approving review is present

2020-10-21 08:31 UTC, NickGeorgiev requested changes
Изглежда добре, браво, че си използвала makefile.

2020-10-21 08:31 UTC, NickGeorgiev commented on group4/81957_Margarita_Mollova/SkipList/Makefile
> +	g++ -c -std=c++14 SkipList.cpp
Слагай по един нов ред накрая на файловете, които нямат

2020-10-21 08:31 UTC, NickGeorgiev commented on group4/81957_Margarita_Mollova/SkipList/SkipList.cpp
> +SkipList::SkipList (const SkipList& other)
Ако инициализираш стойностите тук, после при копирането няма нужда да ги задаваш изрично

2020-10-21 08:31 UTC, NickGeorgiev commented on group4/81957_Margarita_Mollova/SkipList/SkipList.cpp
> +    while (start)
Накрая нулирай start

2020-10-21 08:31 UTC, NickGeorgiev commented on group4/81957_Margarita_Mollova/SkipList/SkipList.cpp
> +size_t SkipList::getNumSkipElements () const
Това защо ти е?

2020-10-21 08:36 UTC, NickGeorgiev commented
За да не добавяте всички библиотеката, сме я включили в папка shared/specs на репото. **specHelper.h** я включва и добавя необходимите макроси, като за тестовете не ти трябва main по начина, по който сме го настроили. Тук https://github.com/NickGeorgiev/sdp-kn-20-21-playground/pull/19 съм ти предложил промени по makefile-a, които да компилират тестовете ти като използват именно specHelper. Ако забравя другия понеделник ми напомни да ви обърна внимание.

Можеш да му направиш едно ревю и ако ти хареса, може да си го налееш при теб.

2020-10-22 08:00 UTC, NickGeorgiev commented
Нещо обаче не виждам и метод **member**

2020-10-22 19:18 UTC, mollova commented on group4/81957_Margarita_Mollova/SkipList/SkipList.cpp
> +size_t SkipList::getNumSkipElements () const
Само заради тестовете го сложих.

2020-10-22 19:21 UTC, mollova commented on group4/81957_Margarita_Mollova/SkipList/SkipList.cpp
> +    while (start)
Но то нали ще излезе от цикъла когато start == nullptr, защо е необходимо да го добавям накрая? Или не разбирам какво имаш предвид?

2020-10-24 12:31 UTC, NickGeorgiev approved these changes

2020-10-24 12:31 UTC, merged